USE ESCOLA

SELECT * FROM [TABELA ALUNO]
SELECT * FROM [TABELA CURSO]
SELECT * FROM [TABELA DISCIPLINA]
SELECT * FROM [TABELA DISCIPLINA X CURSO]
SELECT * FROM [TABELA PAGAMENTOS]
SELECT * FROM [TABELA PROFESSOR]
SELECT * FROM [TABELA TURMA]

-- VIEWS
SELECT * FROM VIEW_INFO_ALUNO

SELECT * FROM BOLETO_ATRASADO

-- PROCEDURES
EXEC ATUALIZA_SIT

EXEC INFO_CURSO_BY_NAME 'THIGAS'
