-- CREATE DATABASE ESCOLA

-- USE ESCOLA

--------- CRIAÇÃO DAS TABELAS ---------
CREATE TABLE [TABELA ALUNO]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(12) UNIQUE,
    DATA_NASC DATE NOT NULL
)

CREATE TABLE [TABELA PROFESSOR]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(12) UNIQUE,
)

CREATE TABLE [TABELA CURSO]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ATIVO BIT DEFAULT 1,
)

CREATE TABLE [TABELA DISCIPLINA]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ATIVO BIT DEFAULT 1,
)

CREATE TABLE [TABELA DISCIPLINA X CURSO]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_CURSO INT FOREIGN KEY REFERENCES [TABELA CURSO](ID),
    ID_DISCIPLINA INT FOREIGN KEY REFERENCES [TABELA DISCIPLINA](ID),
    ATIVA BIT DEFAULT 1,
)


CREATE TABLE [TABELA TURMA]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_ALUNO INT FOREIGN KEY REFERENCES [TABELA ALUNO](ID),
    ID_PROFESSOR INT FOREIGN KEY REFERENCES [TABELA PROFESSOR](ID),
    ID_DISCIPLINA_CURSO INT FOREIGN KEY REFERENCES [TABELA DISCIPLINA X CURSO](ID),
    NOTA1 FLOAT DEFAULT NULL,
    NOTA2 FLOAT,
    NOTA3 FLOAT,
    NOTA4 FLOAT,
    NOTAFINAL INT,
    ATIVA BIT DEFAULT 1,
)

CREATE TABLE [TABELA PAGAMENTOS]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_ALUNO INT FOREIGN KEY REFERENCES [TABELA ALUNO](ID),
    BOLETO DATE NOT NULL,
    SITUACAO VARCHAR(20) NOT NULL,
    CHECK(SITUACAO IN ('PENDENTE','PAGO','EM ATRASO'))
)
