
CREATE OR ALTER TRIGGER ATUALIZA_FATURAMENTO
ON [ITENS NOTAS FISCAIS]
AFTER INSERT
AS 
    BEGIN
        DECLARE @SOMA MONEY 

        SELECT @SOMA = SUM(INF.PREÇO * INF.QUANTIDADE) 
            FROM [ITENS NOTAS FISCAIS] INF

        INSERT INTO FATURAMENTO (VALORATUAL) VALUES(@SOMA) 
    END
